"""add vehicle_id col to gpsdata

Revision ID: 78b6d0c11eac
Revises: 80a475cc9eb9
Create Date: 2025-07-13 20:18:11.752627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '78b6d0c11eac'
down_revision: Union[str, Sequence[str], None] = '80a475cc9eb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gps_data', sa.Column('vehicle_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gps_data', 'vehicle_id')
    # ### end Alembic commands ###
